[tools]
bat = "latest"
bun = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
herdr = "latest"
jq = "latest"
lazygit = "latest"
mas = "latest"
maven = "latest"
minikube = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pandoc = "latest"
pi = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
zoxide = "latest"
